image: node:20.9.0

pages:
  stage: deploy
  image: node:21.6.0
  tags:
    - k8s-vk-karpov-lab-with-npm-proxy
  before_script:
    - npm install
  script:
    - npm run build
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
